//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateIT.ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateIT.ViewResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresy.
        /// </summary>
        public static string Adresy {
            get {
                return ResourceManager.GetString("Adresy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktor.
        /// </summary>
        public static string Aktor {
            get {
                return ResourceManager.GetString("Aktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktorzy i postacie.
        /// </summary>
        public static string AktorzyIPostacie {
            get {
                return ResourceManager.GetString("AktorzyIPostacie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceny.
        /// </summary>
        public static string Ceny {
            get {
                return ResourceManager.GetString("Ceny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane adresowe kontrahenta.
        /// </summary>
        public static string DaneAdresoweKontrahenta {
            get {
                return ResourceManager.GetString("DaneAdresoweKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane firmy TranslateIT.
        /// </summary>
        public static string DaneFirmy {
            get {
                return ResourceManager.GetString("DaneFirmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane projektu.
        /// </summary>
        public static string DaneProjektu {
            get {
                return ResourceManager.GetString("DaneProjektu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość.
        /// </summary>
        public static string Dlugosc {
            get {
                return ResourceManager.GetString("Dlugosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe.
        /// </summary>
        public static string Dodatkowe {
            get {
                return ResourceManager.GetString("Dodatkowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe informacje handlowe.
        /// </summary>
        public static string DodatkoweInformacjeHandlowe {
            get {
                return ResourceManager.GetString("DodatkoweInformacjeHandlowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubbing.
        /// </summary>
        public static string Dubbing {
            get {
                return ResourceManager.GetString("Dubbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 2.
        /// </summary>
        public static string EMail2 {
            get {
                return ResourceManager.GetString("EMail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 3.
        /// </summary>
        public static string EMail3 {
            get {
                return ResourceManager.GetString("EMail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail CC.
        /// </summary>
        public static string EMailCC {
            get {
                return ResourceManager.GetString("EMailCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura.
        /// </summary>
        public static string Faktura {
            get {
                return ResourceManager.GetString("Faktura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktury.
        /// </summary>
        public static string Faktury {
            get {
                return ResourceManager.GetString("Faktury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film.
        /// </summary>
        public static string Film {
            get {
                return ResourceManager.GetString("Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma płatności.
        /// </summary>
        public static string FormaPlatnosci {
            get {
                return ResourceManager.GetString("FormaPlatnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haczyki.
        /// </summary>
        public static string Haczyki {
            get {
                return ResourceManager.GetString("Haczyki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlowe.
        /// </summary>
        public static string Handlowe {
            get {
                return ResourceManager.GetString("Handlowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię i nazwisko.
        /// </summary>
        public static string ImieINazwisko {
            get {
                return ResourceManager.GetString("ImieINazwisko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imiona rodziców.
        /// </summary>
        public static string ImionaRodzicow {
            get {
                return ResourceManager.GetString("ImionaRodzicow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InformacjeDodatkowe.
        /// </summary>
        public static string InformacjeDodatkowe {
            get {
                return ResourceManager.GetString("InformacjeDodatkowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inne.
        /// </summary>
        public static string Inne {
            get {
                return ResourceManager.GetString("Inne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string Kategoria {
            get {
                return ResourceManager.GetString("Kategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria pomocnicza.
        /// </summary>
        public static string KategoriaPomocnicza {
            get {
                return ResourceManager.GetString("KategoriaPomocnicza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient aktywny.
        /// </summary>
        public static string KlienAktywny {
            get {
                return ResourceManager.GetString("KlienAktywny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakty.
        /// </summary>
        public static string Kontakty {
            get {
                return ResourceManager.GetString("Kontakty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahenci.
        /// </summary>
        public static string Kontrahenci {
            get {
                return ResourceManager.GetString("Kontrahenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahent.
        /// </summary>
        public static string Kontrahent {
            get {
                return ResourceManager.GetString("Kontrahent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lektor.
        /// </summary>
        public static string Lektor {
            get {
                return ResourceManager.GetString("Lektor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit kupiecki.
        /// </summary>
        public static string LimitKupiecki {
            get {
                return ResourceManager.GetString("LimitKupiecki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista promocji.
        /// </summary>
        public static string ListaPromocji {
            get {
                return ResourceManager.GetString("ListaPromocji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napisy.
        /// </summary>
        public static string Napisy {
            get {
                return ResourceManager.GetString("Napisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Nazwa {
            get {
                return ResourceManager.GetString("Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string NIP {
            get {
                return ResourceManager.GetString("NIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatki na temat klienta.
        /// </summary>
        public static string NotatkiNaTematKlienta {
            get {
                return ResourceManager.GetString("NotatkiNaTematKlienta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy kontrahent.
        /// </summary>
        public static string NowyKontrahent {
            get {
                return ResourceManager.GetString("NowyKontrahent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obroty.
        /// </summary>
        public static string Obroty {
            get {
                return ResourceManager.GetString("Obroty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogólne.
        /// </summary>
        public static string Ogolne {
            get {
                return ResourceManager.GetString("Ogolne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Opis {
            get {
                return ResourceManager.GetString("Opis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba fizyczna.
        /// </summary>
        public static string OsobaFizyczna {
            get {
                return ResourceManager.GetString("OsobaFizyczna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba kontaktowa.
        /// </summary>
        public static string OsobaKontaktowa {
            get {
                return ResourceManager.GetString("OsobaKontaktowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesel.
        /// </summary>
        public static string Pesel {
            get {
                return ResourceManager.GetString("Pesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik.
        /// </summary>
        public static string Plik {
            get {
                return ResourceManager.GetString("Plik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliki.
        /// </summary>
        public static string Pliki {
            get {
                return ResourceManager.GetString("Pliki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PodmiotGospodarczy.
        /// </summary>
        public static string PodmiotGospodarczy {
            get {
                return ResourceManager.GetString("PodmiotGospodarczy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowe dane Aktora.
        /// </summary>
        public static string PodstawoweDaneAktora {
            get {
                return ResourceManager.GetString("PodstawoweDaneAktora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowe dane kontrahenta.
        /// </summary>
        public static string PodstawoweDaneKontrahenta {
            get {
                return ResourceManager.GetString("PodstawoweDaneKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowe dane Reżysera.
        /// </summary>
        public static string PodstawoweDaneRezysera {
            get {
                return ResourceManager.GetString("PodstawoweDaneRezysera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowe dane Tłumacza.
        /// </summary>
        public static string PodstawoweDaneTlumacza {
            get {
                return ResourceManager.GetString("PodstawoweDaneTlumacza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokazuj nieaktywne osoby.
        /// </summary>
        public static string PokazujNieaktywneOsoby {
            get {
                return ResourceManager.GetString("PokazujNieaktywneOsoby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorytet.
        /// </summary>
        public static string Priorytet {
            get {
                return ResourceManager.GetString("Priorytet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program lojalnościowy.
        /// </summary>
        public static string ProgramLojalnosciowy {
            get {
                return ResourceManager.GetString("ProgramLojalnosciowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przetargi.
        /// </summary>
        public static string Przetargi {
            get {
                return ResourceManager.GetString("Przetargi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudonim.
        /// </summary>
        public static string Pseudonim {
            get {
                return ResourceManager.GetString("Pseudonim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabat.
        /// </summary>
        public static string Rabat {
            get {
                return ResourceManager.GetString("Rabat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabaty.
        /// </summary>
        public static string Rabaty {
            get {
                return ResourceManager.GetString("Rabaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regon.
        /// </summary>
        public static string Regon {
            get {
                return ResourceManager.GetString("Regon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj.
        /// </summary>
        public static string Rodzaj {
            get {
                return ResourceManager.GetString("Rodzaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozliczenia.
        /// </summary>
        public static string Rozliczenia {
            get {
                return ResourceManager.GetString("Rozliczenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanowisko.
        /// </summary>
        public static string Stanowisko {
            get {
                return ResourceManager.GetString("Stanowisko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stawka.
        /// </summary>
        public static string Stawka {
            get {
                return ResourceManager.GetString("Stawka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologie produkcji pieczątek.
        /// </summary>
        public static string TechnologieProdukcjiPieczatek {
            get {
                return ResourceManager.GetString("TechnologieProdukcjiPieczatek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon komórkowy.
        /// </summary>
        public static string TelefonKomorkowy {
            get {
                return ResourceManager.GetString("TelefonKomorkowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin płatności.
        /// </summary>
        public static string TerminPlatnosci {
            get {
                return ResourceManager.GetString("TerminPlatnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tlumacz.
        /// </summary>
        public static string Tlumacz {
            get {
                return ResourceManager.GetString("Tlumacz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tlumacze.
        /// </summary>
        public static string Tlumacze {
            get {
                return ResourceManager.GetString("Tlumacze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twórca.
        /// </summary>
        public static string Tworca {
            get {
                return ResourceManager.GetString("Tworca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Tytul {
            get {
                return ResourceManager.GetString("Tytul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urządzenia.
        /// </summary>
        public static string Urzadzenia {
            get {
                return ResourceManager.GetString("Urzadzenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zleceniobiorca.
        /// </summary>
        public static string Zleceniobiorca {
            get {
                return ResourceManager.GetString("Zleceniobiorca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zleceniodawca.
        /// </summary>
        public static string Zleceniodawca {
            get {
                return ResourceManager.GetString("Zleceniodawca", resourceCulture);
            }
        }
    }
}
